const UPLOAD_MAX_FILE_SIZE_MB = 5;
const UPLOAD_MAX_FILE_SIZE = UPLOAD_MAX_FILE_SIZE_MB * 1024 * 1024;

const UPLOAD_PUBLIC_PATH = '/uploads/profiles';
const VERIFICATION_DOCUMENT_PUBLIC_PATH = '/uploads/landlord-verifications';
const PROPERTY_IMAGES_PUBLIC_PATH = '/uploads/properties';

const MAX_PROPERTY_IMAGES = 10;

const ALLOWED_IMAGE_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
];

const ALLOWED_VERIFICATION_DOCUMENT_TYPES = [
  ...ALLOWED_IMAGE_TYPES,
  'application/pdf',
];

module.exports = {
  UPLOAD_MAX_FILE_SIZE_MB,
  UPLOAD_MAX_FILE_SIZE,
  UPLOAD_PUBLIC_PATH,
  VERIFICATION_DOCUMENT_PUBLIC_PATH,
  PROPERTY_IMAGES_PUBLIC_PATH,
  MAX_PROPERTY_IMAGES,
  ALLOWED_IMAGE_TYPES,
  ALLOWED_VERIFICATION_DOCUMENT_TYPES,
};
